apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd-system
spec:
  project: default
  source:
    repoURL: https://github.com/ymarupudi/argocd.git
    targetRevision: master   # HEAD
    path: app-config/   # Branch Name
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
